# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 前端技术栈
brief-intro: 有关前端的博客
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://github.com/huangfuchunfeng/huangfuchunfeng.github.io' # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

username: 皇甫春风

# other links
#facebook_username: gaohaoyang.water
github_username: huangfuchunfeng
email: huangfu_chunfeng@outlook.com
#weibo_username: 3115521wh
#zhihu_username: gaohaoyang
linkedIn_username: 皇甫春风
#dribbble_username:

description_footer: 前端技术栈

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #Springblog
disqus_shortname: huangfuchunfeng

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 65a13c14df52abcc84e1ea3a69ee4eb0
#google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6

#weeks

zh_weeks: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']

theme: jekyll-theme-architect
